### ISSUE TITLE
As a sales person I want modify Sales order 

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#13] opened 2016-10-01 17:18 UTC

**Comment by lcabrini** [comment] 2016-10-01 22:14
Not written as a user story

**Comment by BorderITS** [comment] 2016-10-01 22:17
OK I will make the changes now

**Comment by lcabrini** [comment] 2016-10-01 22:20
Hm.. didn't this change the whole story. Now it is a duplicate of #15

**Comment by BorderITS** [comment] 2016-10-01 22:55
hmmm... i will see to it

**Closed** 2016-12-03 13:08 UTC
Labels: Sales
